### ISSUE TITLE
Update firefox to 60.6.3

### ISSUE THREAD

**Issue by Z5T1** [cucumberlinux/ports#109]
This update reenables extensions. See https://www.mozilla.org/en-US/firefox/60.6.3/releasenotes/.

**Comment by icampbell-rit** [comment]
Hey @Z5T1 I was just wondering how to fix Error 1 when building firefox. I installed firefox but when I went to build it and it says that there is no rust compiler. Do we need that? Does cucumber support rust? Or should I edit the build info file to not need that.

**Comment by Z5T1** [comment]
Yes, rustc is required to compile Firefox since version 57. Cucumber 2.0 does have a rustc package that provides the rust compiler. I believe it should be installed by default, but if not go ahead and pickle it.

**Comment by icampbell-rit** [comment]
Hey @Z5T1 so there is a ton of other errors now like pangoft2, pango, etc... that are also not installed. Is there a way to install all the things I need for firefox in one go?

**Comment by Z5T1** [comment]
Yeah there are a couple of ways. You can run `portmake build-recursive`, which will compile the required packages from source, or look at the BUILDDEPS variable in firefox.buildinfo and install those packages with pickle.

**Comment by Z5T1** [comment]
Superseded by #119
