### ISSUE TITLE
Update MariaDB to 10.3.14

### ISSUE THREAD

**Issue by Z5T1** [cucumberlinux/ports#66]

**Comment by Z5T1** [comment]
Fixed in #85

**Comment by Z5T1** [comment]
Build failure on x86_64:

```
[ 92%] Built target udf_example
[ 98%] Built target sql_embedded
[ 98%] Built target mysqlserver
[ 98%] Built target symlink_libmysqld.a
[ 98%] Linking CXX shared library libmariadbd.so
/usr/bin/ld: /usr/lib64/gcc/x86_64-cucumber-linux/7.3.0/../../../../lib64/liblzo2.a(lzo1x_1o.o): relocation R_X86_64_PC32 against symbol `memset@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [libmysqld/CMakeFiles/libmysqld.dir/build.make:88: libmysqld/libmariadbd.so.19] Error 1
make[1]: *** [CMakeFiles/Makefile2:12689: libmysqld/CMakeFiles/libmysqld.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

This appears to be a conflict with the lzo-2.10 package. I have built MariaDB 10.3.14 against lzo-2.09 on Cucumber 1.1 without issue. The last time MariaDB was built on CL2.0 was in January, before the initial build of LZO. Interestingly enough, it still builds without issue on i686.

@icampbell-rit I know you were experiencing similar issues. How did you get it to build for you? I'd hate to have to disable LZO support.

**Comment by icampbell-rit** [comment]
@Z5T1 So I was able to build it in my new clone of Cucumber Linux and it did in fact work. But something is not right. Because Daniel could not build it properly. There must be something weird about this update. It now appears it only worked on my cucumber Linux version. Which is quite strange. 

For building I just used the standard Portmake tools and installed the package. It must have some sort of compatibility issue??

**Comment by Z5T1** [comment]
Yeah that's what it looks like. Did you and @QuietImCoding have the lzo package installed at build time?

**Comment by Z5T1** [comment]
Just discovered a bug: #90. I believe this may be related. Since i686 doesn't require PIC, it would make sense that it is still able to link statically with the liblzo2.a file without issue. This would cause issues on x86_64 though since that is PIC by default. I will try rebuilding lzo with --enable-shared and see if that fixes this issue as well.

**Comment by Z5T1** [comment]
That did it!
